[package]
name = "plus-ou-moins"
version = "2.0.0"
description = "Un petit jeu un rust"
authors = ["Woomy4680-exe <github@woomy.ovh>"]
edition = "2018"

[dependencies]
rand = "0.8.3"

[profile.release]
lto = true
overflow-checks = false
